### ISSUE TITLE
TypeError: this.emit is not a function

### ISSUE THREAD

**Issue by Rukkaitto** [jsnanigans/bloc-react#1]
I'm getting this error when emit is called from a Cubit.
This repository has a minimal reproduction sample : https://github.com/Rukkaitto/CleanProject

**Comment by jsnanigans** [comment]
Hey @Rukkaitto thanks for trying out this project!
I'm super excited to get the first issue,
You already closed it, but I will add an answer for others who might come along:

You are probably using the normal method definition like:
```ts
class X extends Cubit {
    //...
    someMethod() {
        this.emit(newState);
    }
}
```
The issue is the same as in classic react class components where you need to bind the method, but the easyest solution is:

turn that into an arrow function:
```ts
class X extends Cubit {
    //...
    someMethod = () => {
        this.emit(newState);
    }
}
```

**Comment by sudoFerraz** [comment]
@jsnanigans Is it possible to use this.emit outside of the constructor of a bloc?

**Comment by jsnanigans** [comment]
@sudoFerraz for a Bloc you there is no `this.emit` thats only available in a Cubit.

for a bloc you would want to use `this.on` to add a listener for an event, then in there you can use the `emit` method you get in the callback, so if you need `this.emit` then you should consider using a `Cubit`

here is an example of a Bloc:

```ts
export enum AuthEvent {
  unknown = "unknown",
  authenticated = "authenticated",
  unauthenticated = "unauthenticated",
}

export default class AuthBloc extends Bloc<AuthEvent, boolean> {
  constructor() {
    super(false)

    this.on(AuthEvent.unknown, (_, emit) => {
      emit(false);
    })
    this.on(AuthEvent.unauthenticated, (_, emit) => {
      emit(false);
    })
    this.on(AuthEvent.authenticated, (_, emit) => {
      emit(true);
    })
  };
}
```
