### ISSUE TITLE
Add the ability to yield multiple state to a stream in mapEventToState like in Flutter

### ISSUE THREAD

**Issue by stijnie2210** [jsnanigans/bloc-react#3]
This package is great, but imo it's missing the critical part which is add multiple state to a stream, would this be possible to make? or is there a limitation in typescript?

Kind of like this
```ts
        this.mapEventToState = (event: MyEvent, emit: Emitter) => {
            switch (event) {
                case MyEvent.specificEvent:
                    emit(new Loading());
                    final result = await myPromise();
                    emit(new Loaded());
            }
        }
```

**Comment by jsnanigans** [comment]
@stijnie2210 thank you for the suggestion, this should already be possible to do with `this.emit`, but the Emitter is not passed to the method yet.

I will try this out in a few testcases to see how best it would work in typescript

-- although I based this package on the dart implementation I dont want to just copy the features blindly. But this feature seems pretty straight forward 👍

**Comment by stijnie2210** [comment]
Hey Brendan,

Thanks for your reply! I did not know it was already possible, I’ll give it
a try to see if I can get it to work. While I’m at it, is it possible you
forgot to export the blocbuilder class in the latest npm version of the
package? I couldn’t seem to import it

**Comment by jsnanigans** [comment]
@stijnie2210 all the react components are part of the `BlocReact` class you create at the moment,

in my `state.ts` file I export them like this:
```ts
const state = new BlocReact();
export const { useBloc, BlocProvider, withBlocProvider, BlocBuilder } = state;
``` 

this is to easily keep track of the context right now, but I would like to improve this that you can just just `import {BlocBuilder} from 'bloc-react'`, but thats not possibly yet

**Comment by jsnanigans** [comment]
@stijnie2210 what I said before was not correct, you cannot use `this.emit` on a Bloc, only in Cubits. I have now update the Bloc implementation to be more like the new [bloclibrary bloc implementation](https://bloclibrary.dev/#/coreconcepts?id=creating-a-bloc) 

Now you can use `this.on(<event>, async (event, emit) => ...)` and use `emit` as many times as you like :) in JS you need to define the function as `async` to use `await`.

I have also update the readme: https://github.com/jsnanigans/bloc-react#bloc

also have a look at this component: https://github.com/jsnanigans/bloc-react/blob/main/src/react/components/LazyToggle.tsx
I have created an example that should fit your use-case nicely

I will close this for now, but please let me know if you have any other issues!

Fixed in https://github.com/jsnanigans/bloc-react/releases/tag/v0.2.0

**Comment by stijnie2210** [comment]
Thanks! You’ve been great help :)
